---
title: Blog of Payne
timezone: UTC
collections:
  play:
    title: Play
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  work:
    title: Work
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: default
- scope:
    path: ''
    type: posts
  values:
    layout: post
- scope:
    path: ''
    type: work
  values:
    layout: post
- scope:
    path: ''
    type: play
  values:
    layout: post
email: noproblemnigel@gmail.com
description: A blog about design
baseurl: 
url: 
twitter_username: tweetsofpayne
github_username: nigelpayne
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
sass:
  style: compressed
